[package]
name = "mandelbrot-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
display-info = "0.5.9"
font8x8 = "0.3.1"
image = { version = "0.25.10", default-features = false, features = ["png"] }
minifb = { version = "0.28.0", default-features = false, features = ["x11"] }
num-complex = "0.4.6"
rayon = "1.12.0"
